// fetch json data api
export const CREATE_TABLE = 'CREATE_TABLE';
// set state variable
export const setTableData = 'setTableData'
export const setDisplayColumns = 'setDisplayColumns';
export const setCurrentPage = 'setCurrentPage';
export const setRecordPerPage = 'setRecordPerPage';
export const setColumnSort = 'setColumnSort';
export const setDragOver = 'setDragOver';
export const setRowHeaderCheckbox = 'setRowHeaderCheckbox';
export const setRowCheckboxFields = 'setRowCheckboxFields';
export const setRowRadioFields = 'setRowRadioFields';
export const setEditCell = 'setEditCell';
export const setExpandedColumns = 'setExpandedColumns';
export const setExpandedRows = 'setExpandedRows';
export const setSortBy = 'setSortBy'
export const setColumnGearFilter = 'setColumnGearFilter'
export const setSelectedGearColumn = 'setSelectedGearColumn'
export const setContextMenu = 'setContextMenu'
export const setContextVisible = 'setContextVisible'
export const setContextX = 'setContextX'
export const setContextY = 'setContextY'
