import BASIC from "./basic";
import {
	PRIMARY_COLOR,
	PRIMARY_SHADE,
	PRIMARY_TINT,
	SECONDARY_COLOR,
	SECONDARY_SHADE,
	SECONDARY_TINT,
	TERTIARY_COLOR,
	TERTIARY_SHADE,
	TERTIARY_TINT,
	TEXT_COLOR,
	TEXT_SHADE,
	TEXT_TINT
} from "app/data";

export default {
	...BASIC,
	background: "white"
};
